[files]
extend-exclude = [
  ".git",
  ".venv",
  "uv.lock"
]

[default.extend-words]
wakatime = "wakatime"
nicholaswilde = "nicholaswilde"
lowlighter = "lowlighter"
shields = "shields"
artifacthub = "artifacthub"
quay = "quay"
yamllint = "yamllint"
markdownlint = "markdownlint"
rumdl = "rumdl"
taskfile = "taskfile"
pyproject = "pyproject"

[default]
extend-ignore-re = [
  # Ignore commit hashes / hex IDs
  "[0-9a-f]{40}"
]
